;;; SPDX-License-Identifier: GPL-3.0-or-later
(define-module (rust-toolchain toml)
  #:use-module (ice-9 hash-table)
  #:use-module (ice-9 textual-ports)
  #:use-module (srfi srfi-1)
  #:export (read-rust-toml))

;; Deliberately restricted TOML, not a general TOML implementation.  Tables,
;; leaf arrays of tables, strings, booleans, and arrays cover Rust dist v2.
;; Unsupported value types and nested array-table semantics fail closed.
(define (read-rust-toml port)
  (let* ((text (get-string-all port)) (size (string-length text)) (pos 0)
         (root (make-hash-table)) (current root)
         (declared (make-hash-table)))
    (define (fail message) (error "Rust TOML" message "at character" pos))
    (define (peek) (and (< pos size) (string-ref text pos)))
    (define (take) (let ((c (peek))) (set! pos (+ pos 1)) c))
    (define (expect c)
      (unless (eqv? (take) c) (fail "unexpected token")))
    (define (space newlines?)
      (let loop ()
        (cond ((memv (peek) (if newlines? '(#\space #\tab #\newline)
                                '(#\space #\tab))) (take) (loop))
              ((and newlines? (eqv? (peek) #\return))
               (take) (expect #\newline) (loop))
              ((eqv? (peek) #\#)
               (let comment ()
                 (when (and (peek) (not (memv (peek) '(#\return #\newline))))
                   (when (or (and (< (char->integer (peek)) 32) (not (eqv? (peek) #\tab)))
                             (= (char->integer (peek)) 127))
                     (fail "control character in comment"))
                   (take) (comment)))
               (when newlines? (loop))))))
    (define (quoted)
      (let ((delimiter (take)))
        (list->string
         (let loop ((chars '()))
           (let ((c (take)))
             (cond ((not c) (fail "unterminated string"))
                   ((eqv? c delimiter) (reverse chars))
                   ((or (and (< (char->integer c) 32) (not (eqv? c #\tab)))
                        (= (char->integer c) 127))
                    (fail "control character in string"))
                   ((and (eqv? delimiter #\") (eqv? c #\\))
                    (let* ((e (take))
                           (simple (assv e '((#\" . #\") (#\\ . #\\)
                                             (#\b . #\backspace) (#\t . #\tab)
                                             (#\n . #\newline) (#\f . #\page)
                                             (#\r . #\return)))))
                      (cond (simple (loop (cons (cdr simple) chars)))
                            ((memv e '(#\u #\U))
                             (let* ((n (if (eqv? e #\u) 4 8))
                                    (digits (list->string
                                             (map (lambda (_)
                                                    (let ((d (take)))
                                                      (unless (and d (string-index "0123456789abcdefABCDEF" d))
                                                        (fail "invalid Unicode escape")) d))
                                                  (iota n))))
                                    (code (string->number digits 16)))
                               (unless (and (<= code #x10ffff)
                                            (not (<= #xd800 code #xdfff)))
                                 (fail "invalid Unicode scalar"))
                               (loop (cons (integer->char code) chars))))
                            (else (fail "unsupported escape")))))
                   (else (loop (cons c chars)))))))))
    (define (key)
      (space #f)
      (if (memv (peek) '(#\" #\')) (quoted)
          (let ((start pos))
            (let loop ()
              (when (and (peek) (or (char<=? #\a (peek) #\z)
                                    (char<=? #\A (peek) #\Z)
                                    (char<=? #\0 (peek) #\9)
                                    (memv (peek) '(#\- #\_))))
                (take) (loop)))
            (when (= start pos) (fail "expected key"))
            (substring text start pos))))
    (define (path)
      (let loop ((keys (list (key))))
        (space #f)
        (if (eqv? (peek) #\.)
            (begin (take) (loop (cons (key) keys))) (reverse keys))))
    (define (parent table keys)
      (fold (lambda (k table)
              (let ((entry (hash-ref table k)))
                (cond ((hash-table? entry) entry)
                      ((hash-get-handle table k) (fail "scalar/array cannot be a parent table"))
                      (else (let ((next (make-hash-table)))
                              (hash-set! table k next) next)))))
            table keys))
    (define (put table k v)
      (when (hash-get-handle table k) (fail "duplicate key"))
      (hash-set! table k v))
    (define (value)
      (space #f)
      (cond ((memv (peek) '(#\" #\')) (quoted))
            ((eqv? (peek) #\[)
             (take) (space #t)
             (let loop ((items '()))
               (if (eqv? (peek) #\]) (begin (take) (reverse items))
                   (let ((v (value)))
                     (space #t)
                     (cond ((eqv? (peek) #\,) (take) (space #t) (loop (cons v items)))
                           ((eqv? (peek) #\]) (take) (reverse (cons v items)))
                           (else (fail "expected comma or array end")))))))
            (else
             (let ((start pos))
               (let loop ()
                 (when (and (peek) (char-alphabetic? (peek))) (take) (loop)))
               (let ((word (substring text start pos)))
                 (cond ((string=? word "true") #t)
                       ((string=? word "false") #f)
                       (else (fail "unsupported or malformed value"))))))))
    (define (assignment table)
      (let ((keys (path)))
        (unless (= 1 (length keys)) (fail "dotted assignments are unsupported; use tables"))
        (expect #\=)
        (put (parent table (drop-right keys 1)) (last keys) (value))))
    (define (header)
      (expect #\[)
      (let* ((array? (eqv? (peek) #\[))
             (_ (when array? (take)))
             (keys (path)) (table (parent root (drop-right keys 1)))
             (k (last keys)) (old (hash-ref table k)))
        (expect #\]) (when array? (expect #\]))
        (if array?
            (begin
              (when (and (hash-get-handle table k)
                         (not (eq? (hash-ref declared keys) 'array)))
                (fail "array-table conflicts with previous definition"))
              (set! current (make-hash-table))
              (hash-set! table k (append (or old '()) (list current)))
              (hash-set! declared keys 'array))
            (begin
              (when (or (hash-ref declared keys)
                        (and (hash-get-handle table k) (not (hash-table? old))))
                (fail "duplicate or conflicting table"))
              (set! current (or old (make-hash-table)))
              (hash-set! table k current)
              (hash-set! declared keys 'table)))))
    (define (plain v)
      (cond ((hash-table? v)
             (sort (hash-map->list (lambda (k v) (cons k (plain v))) v)
                   (lambda (a b) (string<? (car a) (car b)))))
            ((list? v) (map plain v)) (else v)))
    (let loop ()
      (space #t)
      (when (peek)
        (if (eqv? (peek) #\[) (header) (assignment current))
        (space #f)
        (cond ((eqv? (peek) #\return) (take) (expect #\newline))
              ((eqv? (peek) #\newline) (take))
              ((peek) (fail "trailing input or unsupported multiline string")))
        (loop)))
    (plain root)))
